version: "3.9"

services:
  database: 
    image: postgres
    deploy: 
      resources:
        limits:
          cpus: "0.50"
          memory: 1024M
        reservations:
          cpus: "0.25"
          memory: 256M
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: rentx
    restart: always
    ports:
      - 3333:3333
      - 9229:9229 
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database
    deploy: 
      resources:
        limits:
          cpus: "0.50"
          memory: 3072M
        reservations:
          cpus: "0.25"
          memory: 2048M
volumes:
  pgdata:
    driver: local